language: node_js
node_js:
  - 10.15.1
cache: npm
sudo: true
addons:
  chrome: stable
  ssh_known_hosts: 68.183.160.56
before_install:
  - openssl aes-256-cbc -K $encrypted_00710b913eb2_key -iv $encrypted_00710b913eb2_iv
    -in deployuser.enc -out .travis/deployuser -d
  - chmod 700 .travis/deployuser
before_script:
  - npm install -g @angular/cli
script:
  - npm run test
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
env:
  global:
    - KEY_PATH=".travis/deployuser"
    - SERVER=68.183.160.56
    - REMOTE_REPO_PATH="/var/www/danielzamorano.pro"
    - DEPLOY_USER="deploy"
    - GIT_USERNAME="Travis CI"
    - GIT_EMAIL="travis@danielzamorano.pro"
    - GIT_COMMIT_MESSAGE="New Deploy"
